imo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('mainsite.urls')),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

] + i18n_patterns (
    path('', include('mainsite.urls', namespace='lang')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
)


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'mainsite'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    # path('signup/', (cache_page(60)(views.signup_view)), name='signup'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('privacypolicy/', views.privacypolicy_view, name='privacypolicy'),
    path('enteringimo/', views.enteringimo_view, name='enteringimo'),
    path('profile/', views.profile_view, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
            template_name='mainsite/profile/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         views.password_change_done, name='password_change_done'),
    path('news_list/', views.news_list_view, name='news_list'),
    path('news/post/<int:pk>', views.news_view, name='post'),
    path('extra/', views.extra_view, name='extra'),
    path('faq/', views.faq_view, name='faq'),
    path('aboutkazan/', views.aboutkazan_view, name='aboutkazan'),
    path('speciality/<int:key>', views.speciality_view, name='speciality'),
    path('triadkey/',  views.triadkey_view, name='triadkey')
]


handler404 = 'mainsite.views.error_404_view'

mainsite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profile, Faq, Speciality, Triadkey
from datetime import date
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhonePrefixSelect
# from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget


class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(label='пароль', widget=forms.PasswordInput(attrs={'class': "main_block_form_textPassword main_block_form_input_12 InputFieldPassword",
                                                                                  'id': "id_password1",
                                                                                  'placeholder': "Пароль",
                                                                                  'onmousedown': "mouseUp(this)",
                                                                                  'onmouseup': "mouseUp(this)",
                                                                                  'onchange': "mouseUp(this)",
                                                                                  'onmouseover': "mouseUp(this)"}))
    password2 = None

    class Meta:
        model = User
        fields = ['username', 'password1']
        widgets = {
            'username':  forms.TextInput(attrs={'class': "main_block_form_input_12 InputFieldName",
                                                'id': "InputFieldName",
                                                'placeholder': "Логин",
                                                'onmousedown': "mouseUp(this)",
                                                'onmouseup': "mouseUp(this)",
                                                'onchange': "mouseUp(this)",
                                                'onmouseover': "mouseUp(this)"}),
            'password1': forms.PasswordInput()
        }


class ProfileForm(forms.ModelForm):
    # phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(initial='GE'))
    phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(initial='RU', attrs={'class': "select main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                                                                 'id': "id_phone",
                                                                                 'data-tel-input': "",
                                                                                 'type': 'tel',
                                                                                 'placeholder': "Ваш номер телефона",
                                                                                 'onmousedown': "mouseUp(this)",
                                                                                 'onmouseup': "mouseUp(this)",
                                                                                 'onchange': "mouseUp(this)",
                                                                                 'onmouseover': "mouseUp(this)", }))

    class Meta:
        model = Profile
        fields = ['name', 'email', 'city', 'country',
                  'gender', 'birthdate', 'phone', 'citizenship']
        widgets = {
            'name': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-howCanICallYou button-Backcolor-text-black",
                                           'id': "id_name",
                                           'placeholder': "Как к Вам обращаться?",
                                           'onmousedown': "mouseUp(this)",
                                           'onmouseup': "mouseUp(this)",
                                           'onchange': "mouseUp(this)",
                                           'onmouseover': "mouseUp(this)", }),
            'email': forms.EmailInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-email button-Backcolor-text-black",
                                             'id': "id_email",
                                             'placeholder': "Ваша электронная почта",
                                             'onmousedown': "mouseUp(this)",
                                             'onmouseup': "mouseUp(this)",
                                             'onchange': "mouseUp(this)",
                                             'onmouseover': "mouseUp(this)", }),
            'city': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-yourLifeSity button-Backcolor-text-black",
                                           'id': "id_city",
                                           'placeholder': "Ваш родной город",
                                           'onmousedown': "mouseUp(this)",
                                           'onmouseup': "mouseUp(this)",
                                           'onchange': "mouseUp(this)",
                                           'onmouseover': "mouseUp(this)", }),
            'country': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                              'id': "id_country",
                                              'placeholder': "Выберите Вашу страну",
                                              'onmousedown': "mouseUp(this)",
                                              'onmouseup': "mouseUp(this)",
                                              'onchange': "mouseUp(this)",
                                              'onmouseover': "mouseUp(this)", }),
            # 'phone': forms.NumberInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr",
            #                                 'id': "id_phone",
            #                                 'data-tel-input': "",
            #                                 'type': 'tel',
            #                                 'placeholder': "Ваш номер телефона",
            #                                 'onmousedown': "mouseUp(this)" ,
            #                                 'onmouseup': "mouseUp(this)" ,
            #                                 'onchange': "mouseUp(this)" ,
            #                                 'onmouseover': "mouseUp(this)",
            #                                 'style': "border-color: green;",}),
            'gender': forms.Select(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                          'id': "id_gender",
                                          'placeholder': "Ваш пол",
                                          'onmousedown': "mouseUp(this)",
                                          'onmouseup': "mouseUp(this)",
                                          'onchange': "mouseUp(this)",
                                          'onmouseover': "mouseUp(this)", }),
            'birthdate': forms.DateInput(attrs={'class': "form-control main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                                'id': "id_birthdate",
                                                # 'readonly': "readonly",
                                                'data-birth-input': "",
                                                'type': "date",
                                                'placeholder': "Ваш день рождения 2000-05-15",
                                                'onmousedown': "mouseUp(this)",
                                                'onmouseup': "mouseUp(this)",
                                                'onchange': "mouseUp(this)",
                                                'onmouseover': "mouseUp(this)", }),
            'citizenship': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                                  'id': "id_citizenship",
                                                  'placeholder': "Вашe гражданство",
                                                  'onmousedown': "mouseUp(this)",
                                                  'onmouseup': "mouseUp(this)",
                                                  'onchange': "mouseUp(this)",
                                                  'onmouseover': "mouseUp(this)", })
        }


class FaqForm(forms.Form):
    from_email = forms.EmailField(required=True)
    name = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)


# class TriadKey(forms.Form):

mainsite/views.py
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, render, redirect
from mainsite.models import Post, Faq, Speciality, Triadkey
from django.contrib.auth.decorators import login_required
from mainsite.business_logic.business_auth import device_router
from mainsite.business_logic.business_auth import user_login
from mainsite.business_logic.business_auth import user_creation
from mainsite.business_logic.business_auth import logout_render
from mainsite.business_logic.business_auth import extra_signup_page
from mainsite.business_logic.business_profile import profile_render
from mainsite.business_logic.business_profile import profile_edit_render
from mainsite.business_logic.business_profile import password_edit_render


def home_page(request):
    last_4_news = Post.objects.order_by()[:4]

    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_content.html',
                        pc_url='mainsite/home/home_page.html',
                        context={'last_4': last_4_news}
    )


def login_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_login.html',
                        pc_url='mainsite/registration/LoginIndex.html',
                        main_logic=user_login
    )


def logout_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/home/home_page.html',
                        main_logic=logout_render
    )


def signup_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_singup.html',
                        pc_url='mainsite/registration/RegesterIndex.html',
                        main_logic=user_creation
    )


def profile_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_profile.html',
                        pc_url='mainsite/profile/profile.html',
                        main_logic=profile_render
    )


def extra_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_extra.html',
                        pc_url='mainsite/registration/ExtraInfo.html',
                        main_logic=extra_signup_page
    )


def privacypolicy_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/privacyPolicy/PrivacyPolicy.html'
    )


def enteringimo_view(request):
    last_4 = Post.objects.order_by()[:4]
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/enteringIMO/EnteringIMO.html',
                        context={'last_4': last_4}
    )


def error_404_view(request, exception):
    return render(request, 'mainsite/404.html')


def faq_view(request):
    questions = Faq.objects.all()
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_faq.html',
                        pc_url='mainsite/faq/faq.html',
                        context={"questions": questions}
    )


@login_required
def profile_edit(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/profile/proflie_edit.html',
                        main_logic=profile_edit_render
    )


@login_required
def password_edit(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/profile/proflie_edit.html',
                        main_logic=password_edit_render
    )


@login_required
def password_change_done(request):
    logout(request)
    return redirect('login_view')


def aboutkazan_view(request):
    question = Faq.objects.order_by()[:5]
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/home/aboutKazan.html',
                        context={'question': question}
    )


def news_list_view(request):
    news = Post.objects.all()
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/news/news_list.html',
                        context={'news': news}
    )


def news_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    last_4 = Post.objects.order_by()[:4]
    context = {
            'post': post,
            'last_4': last_4,
    }
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/news/news.html',
                        context=context
    )


def speciality_view(request, key):
    speciality = get_object_or_404(Speciality, key=key)
    last_n = Triadkey.objects.order_by()[:4]
    context = {
            'speciality': speciality,
            'last_n': last_n,
        }
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_incomigIMO.html',
                        pc_url='mainsite/incomingIMO/incomingIMO.html',
                        context=context
    )



def triadkey_view(request):
    triadkey = Triadkey.objects.all()
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_incomigIMO.html',
                        pc_url='mainsite/incomingIMO/triadkey.html',
                        context={'triadkey': triadkey}
    )

mainsite/templates/mainsite/PhonePage/phone_enteringimo.html
{% extends 'mainsite/PhonePage/home_page.html' %}{% block content %}
{% load static %}


<body>

    <body class="body">
        <div class="headerTwoEnteringImo_phone">
            <div class="headerTwoEnteringImo_place_phone">
                <div class="headerTwoEnteringImo_box_h1">
                    <h1 class="headerTwoEnteringImo_notbox_h1_phone MargStart">
                        Поступающим в ИМО
                    </h1>
                </div>
            </div>
        </div>

        <div class="headerTwoEnteringImo_Information_phone">
            <div class="headerTwoEnteringImo_column_box_phone borderTop">
                <div class="headerTwoEnteringImo_column_box_p_box_flex_phone">
                    <a href="https://abiturientu.kai.ru/normativnye-dokumenty"
                        class="headerTwoEnteringImo_column_box_p_phone">Нормативные документы</a>
                </div>
            </div>

            <div class="headerTwoEnteringImo_column_box_phone">
                <div class="headerTwoEnteringImo_column_box_p_box_flex_phone">
                    <a href="https://abiturientu.kai.ru/prohodnye-bally"
                        class="headerTwoEnteringImo_column_box_p_phone">Проходные баллы</a>
                </div>
            </div>
            <div class="headerTwoEnteringImo_column_box_phone">
                <div class="headerTwoEnteringImo_column_box_p_box_flex_phone">
                    <a href="{% url 'mainsite:home_page' %}" class="headerTwoEnteringImo_column_box_p_phone">Специальности для
                        поступления</a>
                </div>
            </div>


            <div class="headerTwoEnteringImo_column_box_phone">
                <div class="headerTwoEnteringImo_column_box_p_box_flex_phone">
                    <a href="https://abiturientu.kai.ru/bakalavriat"
                        class="headerTwoEnteringImo_column_box_p_phone">Какие
                        документы требуются для поступления?</a>
                </div>
            </div>
            <div class="headerTwoEnteringImo_column_box_phone">
                <div class="headerTwoEnteringImo_column_box_p_box_flex_phone">
                    <a href="https://www.who.int/ru/emergencies/diseases/novel-coronavirus-2019"
                        class="headerTwoEnteringImo_column_box_p_phone">Информация о Covid 19</a>
                </div>
            </div>
            <div class="headerTwoEnteringImo_column_box_phone">
                <div class="headerTwoEnteringImo_column_box_p_box_flex_phone">
                    <a href="https://abiturientu.kai.ru/kalendar-priema"
                        class="headerTwoEnteringImo_column_box_p_phone">Календарь приема</a>
                </div>
            </div>

        </div>

        <div class="live_in_sharaga_phone">
            <div class="live_in_sharaga_phone_text">
                <div>
                    <h1 class="live_in_sharaga_phone_text_h MargStart">Жизнь в университете</h1>
                </div>
            </div>
            <div class="live_in_sharaga_boxIMG_phone live_in_sharaga_boxIMG_phone_img1 cursor"
                onclick="location.href='/aboutkazan'">
                <a class="live_in_sharaga_boxIMG_a_phone">
                    О Казани
                </a>
            </div>
            <div class="live_in_sharaga_boxIMG_bottom">
            </div>
        </div>

        <div class="base_content_slade3 Mtop31">
            <div>
                <h1 class="weHAve_new_h1 Lang-standart27 MargStart">Наши новости</h1>
            </div>
            <div class="post-last4phone">
                {% for news in last_4 %}
                <a class="news_list_a" href="{% url 'mainsite:post' pk=news.pk %}">
                    <div class="news_block_phone">
                        {% if news.cover_image %}
                        <img src="{{ news.cover_image.url }}" class="news_block_img_phone" />
                        {% endif %}
                        <div class="news_image">

                        </div>
                        <div class="news_info">
                            <div class="news_title">
                                <h3 class="news_title_h3">{{ news.title }}</h3>
                            </div>
                            <div class="news_addititonal_info">
                                <div class="news_KAI_phone">
                                    <div class="news-KAI-block">
                                        <img src="{% static 'mainsite/img/Subtract.svg' %}" alt=""
                                            class="news-KAI-block-IMG">
                                        <p>ИМО КНИТУ-КАИ</p>
                                    </div>
                                    <div class="news-date">
                                        {{ news.published_date }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </body>

    <style>
        .live_in_sharaga_phone_text {
            width: 100%;
            display: flex;
            flex-direction: row;
            justify-content: flex-start;
            align-items: flex-start;
        }

        .live_in_sharaga_phone_text_h {
            font-style: normal;
            font-weight: 700;

            line-height: 23px;

            color: #000000;
        }

        .live_in_sharaga_boxIMG_phone {
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center;
            display: flex;
            justify-content: flex-start;
            align-content: flex-end;
            flex-direction: row;
            align-items: flex-end;
            box-shadow: inset 0px -10px 4px rgba(0, 0, 0, 0.25);
        }

        .live_in_sharaga_boxIMG_phone_img1 {
            background-image: url("{% static '/mainsite/img/phone_enteringimo.svg' %}");

        }

        .headerTwoEnteringImo_Information_phone {
            width: 100%;
            display: grid;
            grid-template-columns: auto auto;
            grid-template-rows: max-content;
        }

        .headerTwoEnteringImo_Information_phone {
            width: 100%;

        }

        .headerTwoEnteringImo_phone {
            width: 100%;
            background-color: #fff;
            margin-top: 30px;
        }

        .headerTwoEnteringImo_column_box_phone {
            display: flex;
            justify-content: center;
            align-items: center;
            border: 1px solid #EBEBEB;
            border-radius: 5px;
            flex-direction: column;
            cursor: pointer;
            text-align: center;
        }

        .headerTwoEnteringImo_column_box_p_phone {
            font-family: 'Averta Demo PE';
            font-style: normal;
            font-weight: 400;
            /* line-height: 15px; */
            color: #000000;
            text-decoration-line: none;
        }

        .headerTwoEnteringImo_notbox_h1_phone {
            font-style: normal;
            font-weight: 700;
            line-height: 22px;
            color: #000000;
        }

        .live_in_sharaga_phone {
            margin-top: 30px;
            width: 100%;
            display: flex;
            justify-content: center;
            flex-direction: column;
            align-items: center;

        }

        .live_in_sharaga_boxIMG_a_phone {

            font-family: var(--font-averta-cy-EB);
            color: #fff;
            text-decoration: none;

        }

        @media screen and (max-width:768px) {
            .live_in_sharaga_boxIMG_a_phone {
                font-size: 15px;
                margin-left: 10px;
                margin-bottom: 10px;
            }

            .live_in_sharaga_phone_text_h {
                font-size: 50px;
            }

            .live_in_sharaga_boxIMG_phone {
                width: 695px;
                height: 192px;

                border-radius: 10px;
                margin-top: 30px;
            }

            .headerTwoEnteringImo_column_box_phone {
                width: 335px;
                height: 158px;
            }

            .headerTwoEnteringImo_column_box_p_phone {
                width: 99px;
                font-size: 25px;
            }

            .headerTwoEnteringImo_notbox_h1_phone {
                font-size: 50px;
            }

            .headerTwoEnteringImo_Information_phone {
                gap: 20px;
            }
        }

        @media screen and (max-width:480px) {
            .live_in_sharaga_boxIMG_a_phone {
                font-size: 15px;
                margin-left: 10px;
                margin-bottom: 10px;
            }

            .live_in_sharaga_phone_text_h {
                font-size: 27px;
            }

            .live_in_sharaga_boxIMG_phone {
                width: 430px;
                height: 120px;

                border-radius: 10px;
            }

            .headerTwoEnteringImo_column_box_phone {
                width: 180px;
                height: 85px;
            }

            .headerTwoEnteringImo_column_box_p_phone {
                width: 99px;
                font-size: 12px;
            }

            .headerTwoEnteringImo_notbox_h1_phone {
                font-size: 27px;
            }

            .headerTwoEnteringImo_Information_phone {
                gap: 20px;
            }
        }

        @media screen and (max-width:360px) {
            .live_in_sharaga_boxIMG_a_phone {
                font-size: 15px;
                margin-left: 10px;
                margin-bottom: 10px;
            }

            .live_in_sharaga_phone_text_h {
                font-size: 18px;
            }

            .live_in_sharaga_boxIMG_phone {
                width: 310px;
                height: 86px;
                border-radius: 10px;
            }

            .headerTwoEnteringImo_column_box_phone {
                width: 145px;
                height: 78px;
            }

            .headerTwoEnteringImo_column_box_p_phone {
                width: 99px;
                font-size: 12px;
            }

            .headerTwoEnteringImo_notbox_h1_phone {
                font-size: 18px;
            }

            .headerTwoEnteringImo_Information_phone {
                gap: 35px;
            }
        }

        @media screen and (max-width:320px) {
            .live_in_sharaga_boxIMG_a_phone {
                font-size: 15px;
                margin-left: 10px;
                margin-bottom: 10px;
            }

            .live_in_sharaga_phone_text_h {
                font-size: 18px;
            }

            .live_in_sharaga_boxIMG_phone {
                width: 288px;
                height: 80px;
                border-radius: 10px;
            }

            .headerTwoEnteringImo_column_box_phone {
                width: 130px;
                height: 78px;
            }

            .headerTwoEnteringImo_column_box_p_phone {
                width: 99px;
                font-size: 12px;
            }

            .headerTwoEnteringImo_notbox_h1_phone {
                font-size: 18px;
            }

            .headerTwoEnteringImo_Information_phone {
                gap: 20px;
            }
        }

        .headerTwoEnteringImo_place_phone {
            width: 100%;
            display: flex;
            justify-content: center;
            flex-direction: column;
        }
    </style>
    {% endblock %}

mainsite/templates/mainsite/PhonePage/phone_faq.html
{% extends 'mainsite/PhonePage/home_page.html' %}{% block content %}
{% load static %}


<body class="body">
    <div class="faq_content_phone">
        <div class="faq_block1_phone">
            <h1>Часто задаваемые вопросы</h1>
        </div>
        {% for question in questions %}
        <div class="faq_question">
            <h3 class="faq_header">
                {{ question.title }}
            </h3>

            <div class="faq_text">
                {{ question.question }}
            </div>

        </div>

        {% endfor %}
        <div class="faq_form">
            <h1>
                Не нашли ответ на свой вопрос?
            </h1>
            <p>Отправьте свои данные, чтобы мы смогли с вами связаться</p>
            <div class="verification-mail_phone">
                <div>
                    <input class="verification-mail-field_phone" type="text" value="imokai@bb.kai.ru" id="myInput" readonly>
                </div>
                <button class="verification-mail-btn" onclick="myFunction()">Скопировать адрес</button>
            </div>
        </div>

    </div>
</body>
<script>
    function myFunction() {
        var copyText = document.getElementById("myInput");
        copyText.select();
        copyText.setSelectionRange(0, 99999)
        document.execCommand("copy");
    }
</script>

{% endblock %}