imo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('mainsite.urls')),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

] + i18n_patterns (
    path('', include('mainsite.urls', namespace='lang')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
)


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'mainsite'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    # path('signup/', (cache_page(60)(views.signup_view)), name='signup'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('privacypolicy/', views.privacypolicy_view, name='privacypolicy'),
    path('enteringimo/', views.enteringimo_view, name='enteringimo'),
    path('profile/', views.profile_view, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
            template_name='mainsite/profile/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         views.password_change_done, name='password_change_done'),
    path('news_list/', views.news_list_view, name='news_list'),
    path('news/post/<int:pk>', views.news_view, name='post'),
    path('extra/', views.extra_view, name='extra'),
    path('faq/', views.faq_view, name='faq'),
    path('aboutkazan/', views.aboutkazan_view, name='aboutkazan'),
    path('speciality/<int:key>', views.speciality_view, name='speciality'),
    path('triadkey/',  views.triadkey_view, name='triadkey')
]


handler404 = 'mainsite.views.error_404_view'

mainsite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profile, Faq, Speciality, Triadkey
from datetime import date
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhonePrefixSelect
# from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget


class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(label='пароль', widget=forms.PasswordInput(attrs={'class': "main_block_form_textPassword main_block_form_input_12 InputFieldPassword",
                                                                                  'id': "id_password1",
                                                                                  'placeholder': "Пароль",
                                                                                  'onmousedown': "mouseUp(this)",
                                                                                  'onmouseup': "mouseUp(this)",
                                                                                  'onchange': "mouseUp(this)",
                                                                                  'onmouseover': "mouseUp(this)"}))
    password2 = None

    class Meta:
        model = User
        fields = ['username', 'password1']
        widgets = {
            'username':  forms.TextInput(attrs={'class': "main_block_form_input_12 InputFieldName",
                                                'id': "InputFieldName",
                                                'placeholder': "Логин",
                                                'onmousedown': "mouseUp(this)",
                                                'onmouseup': "mouseUp(this)",
                                                'onchange': "mouseUp(this)",
                                                'onmouseover': "mouseUp(this)"}),
            'password1': forms.PasswordInput()
        }


class ProfileForm(forms.ModelForm):
    # phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(initial='GE'))
    phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(initial='RU', attrs={'class': "select main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                                                                 'id': "id_phone",
                                                                                 'data-tel-input': "",
                                                                                 'type': 'tel',
                                                                                 'placeholder': "Ваш номер телефона",
                                                                                 'onmousedown': "mouseUp(this)",
                                                                                 'onmouseup': "mouseUp(this)",
                                                                                 'onchange': "mouseUp(this)",
                                                                                 'onmouseover': "mouseUp(this)", }))

    class Meta:
        model = Profile
        fields = ['name', 'email', 'city', 'country',
                  'gender', 'birthdate', 'phone', 'citizenship']
        widgets = {
            'name': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-howCanICallYou button-Backcolor-text-black",
                                           'id': "id_name",
                                           'placeholder': "Как к Вам обращаться?",
                                           'onmousedown': "mouseUp(this)",
                                           'onmouseup': "mouseUp(this)",
                                           'onchange': "mouseUp(this)",
                                           'onmouseover': "mouseUp(this)", }),
            'email': forms.EmailInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-email button-Backcolor-text-black",
                                             'id': "id_email",
                                             'placeholder': "Ваша электронная почта",
                                             'onmousedown': "mouseUp(this)",
                                             'onmouseup': "mouseUp(this)",
                                             'onchange': "mouseUp(this)",
                                             'onmouseover': "mouseUp(this)", }),
            'city': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-yourLifeSity button-Backcolor-text-black",
                                           'id': "id_city",
                                           'placeholder': "Ваш родной город",
                                           'onmousedown': "mouseUp(this)",
                                           'onmouseup': "mouseUp(this)",
                                           'onchange': "mouseUp(this)",
                                           'onmouseover': "mouseUp(this)", }),
            'country': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                              'id': "id_country",
                                              'placeholder': "Выберите Вашу страну",
                                              'onmousedown': "mouseUp(this)",
                                              'onmouseup': "mouseUp(this)",
                                              'onchange': "mouseUp(this)",
                                              'onmouseover': "mouseUp(this)", }),
            # 'phone': forms.NumberInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr",
            #                                 'id': "id_phone",
            #                                 'data-tel-input': "",
            #                                 'type': 'tel',
            #                                 'placeholder': "Ваш номер телефона",
            #                                 'onmousedown': "mouseUp(this)" ,
            #                                 'onmouseup': "mouseUp(this)" ,
            #                                 'onchange': "mouseUp(this)" ,
            #                                 'onmouseover': "mouseUp(this)",
            #                                 'style': "border-color: green;",}),
            'gender': forms.Select(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                          'id': "id_gender",
                                          'placeholder': "Ваш пол",
                                          'onmousedown': "mouseUp(this)",
                                          'onmouseup': "mouseUp(this)",
                                          'onchange': "mouseUp(this)",
                                          'onmouseover': "mouseUp(this)", }),
            'birthdate': forms.DateInput(attrs={'class': "form-control main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                                'id': "id_birthdate",
                                                # 'readonly': "readonly",
                                                'data-birth-input': "",
                                                'type': "date",
                                                'placeholder': "Ваш день рождения 2000-05-15",
                                                'onmousedown': "mouseUp(this)",
                                                'onmouseup': "mouseUp(this)",
                                                'onchange': "mouseUp(this)",
                                                'onmouseover': "mouseUp(this)", }),
            'citizenship': forms.TextInput(attrs={'class': "main_block_form_textName main_block_form_input_1 Iamastud_FORM1 LengText-selectYourCountr button-Backcolor-text-black",
                                                  'id': "id_citizenship",
                                                  'placeholder': "Вашe гражданство",
                                                  'onmousedown': "mouseUp(this)",
                                                  'onmouseup': "mouseUp(this)",
                                                  'onchange': "mouseUp(this)",
                                                  'onmouseover': "mouseUp(this)", })
        }


class FaqForm(forms.Form):
    from_email = forms.EmailField(required=True)
    name = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)


# class TriadKey(forms.Form):

mainsite/views.py
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, render, redirect
from mainsite.models import Post, Faq, Speciality, Triadkey
from django.contrib.auth.decorators import login_required
from mainsite.business_logic.business_auth import device_router
from mainsite.business_logic.business_auth import user_login
from mainsite.business_logic.business_auth import user_creation
from mainsite.business_logic.business_auth import logout_render
from mainsite.business_logic.business_auth import extra_signup_page
from mainsite.business_logic.business_profile import profile_render
from mainsite.business_logic.business_profile import profile_edit_render
from mainsite.business_logic.business_profile import password_edit_render


def home_page(request):
    last_4_news = Post.objects.order_by()[:4]

    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_content.html',
                        pc_url='mainsite/home/home_page.html',
                        context={'last_4': last_4_news}
    )


def login_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_login.html',
                        pc_url='mainsite/registration/LoginIndex.html',
                        main_logic=user_login
    )


def logout_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/home/home_page.html',
                        main_logic=logout_render
    )


def signup_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_singup.html',
                        pc_url='mainsite/registration/RegesterIndex.html',
                        main_logic=user_creation
    )


def profile_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_profile.html',
                        pc_url='mainsite/profile/profile.html',
                        main_logic=profile_render
    )


def extra_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_extra.html',
                        pc_url='mainsite/registration/ExtraInfo.html',
                        main_logic=extra_signup_page
    )


def privacypolicy_view(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/privacyPolicy/PrivacyPolicy.html'
    )


def enteringimo_view(request):
    last_4 = Post.objects.order_by()[:4]
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/enteringIMO/EnteringIMO.html',
                        context={'last_4': last_4}
    )


def error_404_view(request, exception):
    return render(request, 'mainsite/404.html')


def faq_view(request):
    questions = Faq.objects.all()
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_faq.html',
                        pc_url='mainsite/faq/faq.html',
                        context={"questions": questions}
    )


@login_required
def profile_edit(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/profile/proflie_edit.html',
                        main_logic=profile_edit_render
    )


@login_required
def password_edit(request):
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/profile/proflie_edit.html',
                        main_logic=password_edit_render
    )


@login_required
def password_change_done(request):
    logout(request)
    return redirect('login_view')


def aboutkazan_view(request):
    question = Faq.objects.order_by()[:5]
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/home/aboutKazan.html',
                        context={'question': question}
    )


def news_list_view(request):
    news = Post.objects.all()
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/news/news_list.html',
                        context={'news': news}
    )


def news_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    last_4 = Post.objects.order_by()[:4]
    context = {
            'post': post,
            'last_4': last_4,
    }
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/index.html',
                        pc_url='mainsite/news/news.html',
                        context=context
    )


def speciality_view(request, key):
    speciality = get_object_or_404(Speciality, key=key)
    last_n = Triadkey.objects.order_by()[:4]
    context = {
            'speciality': speciality,
            'last_n': last_n,
        }
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_incomigIMO.html',
                        pc_url='mainsite/incomingIMO/incomingIMO.html',
                        context=context
    )



def triadkey_view(request):
    triadkey = Triadkey.objects.all()
    return device_router(
                        request,
                        mobile_url='mainsite/PhonePage/phone_incomigIMO.html',
                        pc_url='mainsite/incomingIMO/triadkey.html',
                        context={'triadkey': triadkey}
    )

mainsite/templates/mainsite/base.html
{% load static %}{% load i18n %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% translate "LangStaticname1" %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" type="image/png" href='{% static "mainsite/img/Icon.svg" %}' />
    <link href='{% static "mainsite/css/registration/login_base_style.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/registration/style_1.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/registration/style_2.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/profile/profile.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/registration/style_3.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/registration/style_4.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/faq/faq.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/news/news.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/news/news_list.css" %}' rel="stylesheet">
    <link href='{% static "mainsite/css/incoming/incoming.css" %}' rel="stylesheet">
    <link href='https://fonts.google.com/specimen/Inter#standard-styles' rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href='{% static "mainsite/css/registration/preloader.css" %}' rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="{% static 'mainsite/js/registration/Them.js' %}">
    </script>
    <script src="{% static 'mainsite/js/registration/ChangeEay.js' %}">
    </script>
    <script src="{% static 'mainsite/js/registration/mouseChange.js' %}">
    </script>
    <script src="{% static 'mainsite/js/registration/changePass.js' %}">
    </script>
    <script src="{% static 'mainsite/js/registration/regesterBUT.js' %}">
    </script>
    <script src="{% static 'mainsite/js/registration/phoneinput.js' %}">
    </script>
    <script src="{% static 'mainsite/js/registration/preloader.js' %}">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js">
    </script>
    <script src="{% static 'mainsite/js/them/them.js' %}">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr">
    </script>
    <script>
        flatpickr("#myID", {});
    </script>
</head>


<div class="preloader">
    <div class="preloader__row">
        <div class="spinner preloader__item"></div>
    </div>
</div>


<header class="header">
    <a href="{% url 'mainsite:home_page' %}">
        <div class="main_icon_logo_flexbox">
            <div class="main_icon_logo">
            </div>
            <p class="main_icon_logo_text">
                {% translate "LangStaticname2" %}
            </p>
        </div>
    </a>

    <div class="menu_links_boxs">
        <div class="menu_links_box_displayWhere700px">
            <div class="menu_links_box_iconWhereDisplay700px">
                <div class="menu_links_box_iconWhereDisplay700pxImgsvg"></div>
            </div>
            <div class="menu_links_box_text700px_box">
                <p class="menu_links_box_text700px">{% translate "LangStaticname3" %}</p>
            </div>
        </div>
        <div class="menu_links_boxs_links">
            <a href="{% url 'mainsite:enteringimo' %}">
                <div class="menu_links_boxs_links_link">
                    <div class="menu_links_boxs_links_link_icon">
                        <div class="standartStyleForimg books"></div>
                    </div>
                    <div class="menu_links_boxs_links_link_iconText_box">
                        <p class="menu_links_boxs_links_link_iconText">#{% translate "LangStaticname4" %}</p>
                    </div>
                </div>
            </a>

            <a href="{% url 'mainsite:faq' %}">
                <div class="menu_links_boxs_links_link">
                    <div class="menu_links_boxs_links_link_icon">
                        <div class="standartStyleForimg key"></div>
                    </div>
                    <div class="menu_links_boxs_links_link_iconText_box">
                        <p class="menu_links_boxs_links_link_iconText">#{% translate "LangStaticname5" %}</p>
                    </div>
                </div>
            </a>

            <a href="{% url 'mainsite:news_list' %}">
                <div class="menu_links_boxs_links_link">
                    <div class="menu_links_boxs_links_link_icon">
                        <div class="standartStyleForimg gun"></div>
                    </div>
                    <div class="menu_links_boxs_links_link_iconText_box">
                        <p class="menu_links_boxs_links_link_iconText">#{% translate "LangStaticname6" %}</p>
                    </div>
                </div>
            </a>

            <div class="buttonsInHeader_box displayNoneWhere displayon clickOnserch">
                <input type="button" class="buttonsInHeader_box_search noStyelButt cursorP" id="search">
                <div class="buttonsInHeader_box_search_TextBox">
                    <p class="buttonsInHeader_box_search_Text">{% translate "LangStaticname7" %}</p>
                </div>
            </div>
            <div class=""><!--buttonsInHeader_box displayNoneWhere clickOnserch-->
                <div class="form-check form-switch">
                    <input class="form-check-input cursor" type="checkbox" id="flexSwitchCheckDefault">
                </div>
            </div>
        </div>
    </div>
    <div class="buttonsInHeader">
        <div class="buttonsInHeader_box displayNoneWhere displayof clickOnserch">
            <input type="button" class="buttonsInHeader_box_search noStyelButt cursorP" id="search">
        </div>
        <nav class="navbar navbar-expand-lg navbar-light btg-light">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Ru
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% get_current_language as LANGUAGE_CODE %}
                      {% get_available_languages as LANGUAGES %}
                      {% get_language_info_list for LANGUAGES as languages %}
          
                      {% for lang in languages %}
                        <li>
                        <a class="dropdown-item" href="/{{ lang.code }}/">
                            {{ lang.name_local }}
                        </a>
                        </li>
                      {% endfor %}
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        <!-- <div class="buttonsInHeader_box"> 
            <input type="button" class="buttonsInHeader_box_lang noStyelButt cursorP Lang-name" id="lang" value="Ru">
        </div> -->
        <div class="headerLanguage" id="hidden_block">
            <div class="russ headerLanguage_flexbox" id="Ru"
                onclick="defineLang(this,document.querySelector('.Lang-name'))">
                <div class="img_active change">
                    <img src='{% static "mainsite/img/ru.png" %}' alt="">
                </div>
                <div class="russ_txt">
                    <p class="defineText">Русский</p>
                </div>
            </div>
            <div class="eng headerLanguage_flexbox" id="Eng"
                onclick="defineLang(this,document.querySelector('.Lang-name'))">
                <div class="img_no_active change">
                    <img src='{% static "mainsite/img/eng.png" %}' alt="">
                </div>
                <div class="eng_txt">
                    <p class="defineText">English</p>
                </div>
            </div>
        </div>
        {% if request.user.is_authenticated %}
            {% if request.user.profile %}
                <div class="buttonsInHeader_box">
                    <input type="button" class="buttonsInHeader_box_usButton noStyelButt cursorP" id="usButton"
                        onclick="location.href='/profile'">
                </div>
            {% else %}
                <div class="buttonsInHeader_box">
                    <input type="button" class="buttonsInHeader_box_usButton noStyelButt cursorP" id="usButton"
                        onclick="location.href='/extra'">
                </div>
            {% endif %}    
        {% else %} 

        <div class="buttonsInHeader_box">
            <input type="button" class="buttonsInHeader_box_usButton noStyelButt cursorP" id="usButton"
                onclick="location.href='/signup'">
        </div>

        {% endif %}
    </div>
</header>
<body>
    {% block content %} {% endblock %}

</body>
<div class="footer" style="margin-top: 100px;">
    <div class="footer_boxs_1 footer_boxs">
        <div class="main_icon_logo_flexbox">
            <div class="main_icon_logo">
            </div>
            <p class="main_icon_logo_text">
                {% translate "LangStaticname2" %}
            </p>
        </div>
        <div class="footer_boxs_links_box">
            <div class="footer_boxs_links_box_plot">
                <div class="footer_boxs_links_box_l footer_boxs_links_box_l1 cursorP"></div>
            </div>
            <div class="footer_boxs_links_box_plot">
                <div class="footer_boxs_links_box_l footer_boxs_links_box_l2 cursorP"></div>
            </div>
            <div class="footer_boxs_links_box_plot">
                <div class="footer_boxs_links_box_l footer_boxs_links_box_l3 cursorP"></div>
            </div>
            <div class="footer_boxs_links_box_plot">
                <div class="footer_boxs_links_box_l footer_boxs_links_box_l4 cursorP"></div>
            </div>
        </div>
    </div>

    <div class="footer_boxs_2 footer_boxs">
        <div class="footer_boxs_boxH3">
            <p class="helpText">{% translate "LangStaticname8" %}</p>
        </div>
        <div class="footer_boxs_textadr">
            <p class="footer_mainText">{% translate "LangStaticname9" %}</p>
        </div>
    </div>
    <div class="footer_boxs_3 footer_boxs">
        <div class="footer_boxs_boxP">
            <p class="helpText">{% translate "LangStaticname10" %}</p>
        </div>
        <div class="footer_boxs_boxH3">
            <h3 class="footer_mainText">+7(843)231-00-27</h3>
        </div>
    </div>
    <div class="footer_boxs_4 footer_boxs">
        <div class="footer_boxs_boxP">
            <p class="helpText">{% translate "LangStaticname11" %}</p>
        </div>
        <div class="footer_boxs_boxH3">
            <h3 class="footer_mainText">+7(843)231-01-58</h3>
        </div>
    </div>
    <div class="footer_boxs_5 footer_boxs">
        <div class="Memo_box_textInf_contentTextsALinks_cont cursorP">
            <p class="Memo_box_textInf_p nowVW">pk@kai.ru</p>
        </div>
        <div class="Memo_box_textInf_contentTextsALinks_cont cursorP">
            <p class="Memo_box_textInf_p nowVW">international@kai.ru</p>
        </div>
    </div>
    <div class="footer_boxHR marginTOP_70px">
        <hr class="footer_hr" />
    </div>

    <div class="footer_FM">
        <div class="footer_FM1">
            <!-- <div class="footer_FM1_Logo">

                </div> -->
            <div class="footer_FM1_boxp">
                <p class="footer_FM1_p">© {% translate "LangStaticname12" %} 2022
                </p>
            </div>
        </div>
        <div class="footer_FM2">
            <div class="footer_FM2 link_FM2 cursorN">
                <p class="link_FM2Text">© {% translate "LangStaticname13" %} 2022</p>
            </div>
        </div>
    </div>
</div>
</html>